NONE_INDICATOR="__none__"
ALL_INDICATOR="__all__"

[PRIVILEGES]
# url squad-admin-configurator
API="http://localhost/"
# полный заголовок авторизации для доступа к squad-admin-configurator, токен вместе с его префиксом
TOKEN="Token <token>"
# Сопоставление названия роли для бота её id в конфигураторе
[PRIVILEGES.ROLES_ID]
vip = 1
seedvip = 3
admin = 2

[DISCORD]
# токен доступа к боту дискорда
TOKEN=""
# id сообществ дискорда, где бот будет работать
GUILDS=[88005553535]
# Группы пользователей который могут просматривать или создавать определенные роли в конфигураторе
# формат:
# [DISCORD.ACTION_ROLES_MAP.<id сообщества>.<действие>]
[DISCORD.ACTION_ROLES_MAP.88005553535.READ]
# others - это правила для тех, чью роль не найдут
# <id роли в discord> - это правила для конкретной роли
# Возможные значения:
# - список ролей по их названиям из раздела PRIVILEGES
# - значение из NONE_INDICATOR если ничего не имеет право получить
# - либо значение из ALL_INDICATOR если пользователь может получить всю информацию
others = "__none__"
1000000000000000000 = ['vip', 'seedvip'] # может смотреть випов
1000000000000000001 = "__all__" # admin, может смотреть всё
[DISCORD.ACTION_ROLES_MAP.88005553535.WRITE]
others = "__none__"
1000000000000000002 = ['admin']
1000000000000000001 = ['moderator']
1000000000000000000 = "__all__"

[TEMPLATES]
# Папка с шаблонами
DIR="./templates/"
# Проверять ли папку с шаблонами на предмет изменения шаблонами
# поставь в false для небольшой прибавке к скорости обработки шаблонов
AUTO_RELOAD=true