FROM python:3.10-alpine3.18

# debug port
EXPOSE 5678

ENV PYTHONDONTWRITEBYTECODE=1

WORKDIR /app

RUN pip3 install debugpy -t /tmp

COPY ./requirements.txt ./

RUN pip3 install -r requirements.txt --no-cache-dir

COPY ./ ./

CMD ["python", "/tmp/debugpy", "--wait-for-client", "--listen", "0.0.0.0:5678", "main.py"]